# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard's Blog
email: rich.hong@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  "A tech blog written by a junior web developer enrolled at Telegraph Academy."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://richHong.github.io" # the base hostname & protocol for your site
twitter_username: richHong81
github_username:  richHong
linkedin_username: richhong

# Build settings
markdown: kramdown
